### ISSUE TITLE
Compile bug: CUDA error: invalid use of ‘extern’ in linkage specification

### ISSUE THREAD

**Issue by dan-and** [TheTom/llama-cpp-turboquant#48]
### Git commit

commit bc05a6803e48f17e0f2c7a99fce9b50d03882de7 (HEAD -> feature/turboquant-kv-cache, origin/feature/turboquant-kv-cache)
Merge: e9c54d557 e43970099

### Operating systems

Linux

### GGML backends

CUDA

### Problem description & steps to reproduce

Just tried to get up to date with the current repository. 

### First Bad Commit

commit bc05a6803e48f17e0f2c7a99fce9b50d03882de7 (HEAD -> feature/turboquant-kv-cache, origin/feature/turboquant-kv-cache)
Merge: e9c54d557 e43970099
Author: TheTom <tturney1@gmail.com>
Date:   Fri Apr 3 12:21:45 2026 -0500

    Merge remote-tracking branch 'origin/master' into feature/turboquant-kv-cache

### Compile command

```shell
cmake -B build -DBUILD_SHARED_LIBS=OFF -DGGML_CUDA=ON -DCMAKE_BUILD_TYPE=Debug
cmake --build build --config Debug -j 10
```

### Relevant log output

```shell
[ 28%] Built target ggml-cuda
In file included from /home/daniel/source/TheTom_llama-cpp-turboquant/ggml/src/ggml-cpu/ops.h:3,
                 from /home/daniel/source/TheTom_llama-cpp-turboquant/ggml/src/ggml-cpu/ops.cpp:1:
/home/daniel/source/TheTom_llama-cpp-turboquant/ggml/src/../include/ggml.h:187:22: error: invalid use of ‘extern’ in linkage specification
  187 | #    define GGML_API extern
      |                      ^~~~~~
/home/daniel/source/TheTom_llama-cpp-turboquant/ggml/src/ggml-cpu/ops.cpp:15:12: note: in expansion of macro ‘GGML_API’
   15 | extern "C" GGML_API int turbo3_cpu_wht_group_size;
      |            ^~~~~~~~
/home/daniel/source/TheTom_llama-cpp-turboquant/ggml/src/ggml-cpu/ops.cpp: In function ‘void ggml_compute_forward_clamp(const ggml_compute_params*, ggml_tensor*)’:
/home/daniel/source/TheTom_llama-cpp-turboquant/ggml/src/ggml-cpu/ops.cpp:5568:12: warning: enumeration value ‘GGML_TYPE_TURBO3_0’ not handled in switch [-Wswitch]
 5568 |     switch (src0->type) {
      |            ^
/home/daniel/source/TheTom_llama-cpp-turboquant/ggml/src/ggml-cpu/ops.cpp:5568:12: warning: enumeration value ‘GGML_TYPE_TURBO4_0’ not handled in switch [-Wswitch]
/home/daniel/source/TheTom_llama-cpp-turboquant/ggml/src/ggml-cpu/ops.cpp:5568:12: warning: enumeration value ‘GGML_TYPE_TURBO2_0’ not handled in switch [-Wswitch]
gmake[2]: *** [ggml/src/CMakeFiles/ggml-cpu.dir/build.make:230: ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/ops.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1893: ggml/src/CMakeFiles/ggml-cpu.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```

**Comment by dan-and** [comment]
Workaround: 



```
diff --git a/ggml/src/ggml-cpu/ops.cpp b/ggml/src/ggml-cpu/ops.cpp
index 6760d0b28..31e807e88 100644
--- a/ggml/src/ggml-cpu/ops.cpp
+++ b/ggml/src/ggml-cpu/ops.cpp
@@ -12,7 +12,13 @@
 #include <cfloat>
 #include <cmath>

-extern "C" GGML_API int turbo3_cpu_wht_group_size;
+extern "C" {
+#if defined(GGML_SHARED) && !(defined(_WIN32) && !defined(__MINGW32__))
+extern GGML_API int turbo3_cpu_wht_group_size;
+#else
+GGML_API int turbo3_cpu_wht_group_size;
+#endif
+}

 // ggml_compute_forward_dup


```

**Comment by signalnine** [comment]
Fix included in PR #53 — addresses both the `extern "C" GGML_API` double-extern and the missing turbo types in the clamp switch.
