### ISSUE TITLE
Compile bug: \llama-cpp-turboquant\ggml\src\ggml-cpu\ops.cpp(22,10): error C2159: more than one storage class specified [\llama-cpp-turboquant\build\ggml\src\ggml-cpu.vcxproj]

### ISSUE THREAD

**Issue by BenCzaczkes** [TheTom/llama-cpp-turboquant#282]
### Git commit

BC23:44:56 0ms C:\PD\0Active\llama-cpp-turboquantgit rev-parse HEAD
2f2f32f5d9517518c9e860f30131acb09840a965
Just thought I should report it. I've been building it from source for quite a long while now. It's the first time something like this happened to me. I'm not quite sure if it's critical. I will have a look at the files. But it's been a while since I used the Microsoft Visual Studio, so might might not be able to find out what's going on

### Operating systems

Windows

### GGML backends

CUDA

### Problem description & steps to reproduce

I'm trying to compile Lama CPP with CUDA support on Windows 11. Here is the script I've been using. I've used this PowerShell script for quite a while now and it's the first time I have a problem with it
git clone https://github.com/TheTom/llama-cpp-turboquant.git
cd llama-cpp-turboquant
git checkout feature/turboquant-kv-cache
md build
cd build
cmake .. -G "Visual Studio 17 2022" -A x64 `
         -DGGML_CUDA=ON `
         -DGGML_CUDA_ARCHITECTURES=120 `
         -DGGML_FLASH_ATTENTION=ON `
         -DLLAMA_BUILD_BORINGSSL=ON `
         -DCMAKE_BUILD_TYPE=Release

cmake --build . --config Release -j $env:NUMBER_OF_PROCESSORS

### First Bad Commit

It didn't happen a couple of weeks ago, but I'm not sure what commit it was

### Compile command

```shell
git clone https://github.com/TheTom/llama-cpp-turboquant.git
cd llama-cpp-turboquant
git checkout feature/turboquant-kv-cache
md build
cd build
cmake .. -G "Visual Studio 17 2022" -A x64 `
         -DGGML_CUDA=ON `
         -DGGML_CUDA_ARCHITECTURES=120 `
         -DGGML_FLASH_ATTENTION=ON `
         -DLLAMA_BUILD_BORINGSSL=ON `
         -DCMAKE_BUILD_TYPE=Release

cmake --build . --config Release -j $env:NUMBER_OF_PROCESSORS
```

### Relevant log output

```shell
The room is 4000 K I copied the one line that was interesting in the subject
```

**Comment by TheTom** [comment]
Fixed on the current branch by 28896c45b. GGML_API now supplies extern for exported declarations, and ops.cpp no longer adds a second extern storage specifier. Please reopen with a current-head build log if MSVC still reports C2159.
