### ISSUE TITLE
Compile bug: hip broken after #84

### ISSUE THREAD

**Issue by xaocon** [TheTom/llama-cpp-turboquant#96]
### Git commit

8ba9f128822b4cef73f5555ca5fcccfbfadbcd20

### Operating systems

Linux

### GGML backends

HIP

### Problem description & steps to reproduce

Compilation fails for hip with recent code. I dropped an example of the issues into the box bellow.

I was able to trace it back to #84 through trial and error and looking at the changes it seems to line up.

### First Bad Commit

90968cc4d702ba53fb643f39e50c2f24bbcee8d8

### Compile command

```shell
HIPCXX="$(hipconfig -l)/clang" HIP_PATH="$(hipconfig -R)" \
    cmake -S . -B build -DGGML_HIP=ON -DGPU_TARGETS=gfx1201 -DCMAKE_BUILD_TYPE=Release -DGGML_CCACHE=OFF \
    && cmake --build build --config Release -- -j 16
```

### Relevant log output

```shell
/usr/bin/ld: ../../bin/libggml-hip.so.0.9.11: undefined reference to `void ggml_cuda_flash_attn_ext_vec_case<128, (ggml_type)1, (ggml_type)43>(ggml_backend_cuda_context&, ggml_tensor*)'
/usr/bin/ld: ../../bin/libggml-hip.so.0.9.11: undefined reference to `void ggml_cuda_flash_attn_ext_vec_case<64, (ggml_type)1, (ggml_type)42>(ggml_backend_cuda_context&, ggml_tensor*)'
/usr/bin/ld: ../../bin/libggml-hip.so.0.9.11: undefined reference to `void ggml_cuda_flash_attn_ext_vec_case<256, (ggml_type)1, (ggml_type)43>(ggml_backend_cuda_context&, ggml_tensor*)'
```

**Comment by taniguchi-taku-softm** [comment]
Try it.
-DGGML_CUDA_FA_ALL_QUANTS=ON

**Comment by xaocon** [comment]
> Try it. -DGGML_CUDA_FA_ALL_QUANTS=ON

Thanks, yeah I ran down the problem and created #97.

**Comment by xaocon** [comment]
fixed in 9e3fb40
