### PR TITLE
Pr/rollup upstream

### PR DESCRIPTION
**Pull request by giveen**
## Overview
This is a roll-up patch needed for MoE caching patches

- AI usage disclosure:  Yes

### CODE REVIEW

**Comment by giveen** [comment]
@TheTom first patch

**Comment by TheTom** [comment]
Thanks for splitting this out, @giveen. 80 commits reads as a lot to review, so I went and measured how much of it is actually yours to review, and the answer is reassuring.

## The review surface is 2 commits, not 80

Of the commits this branch adds over `feature/turboquant-kv-cache`:

- **78 are non-merge commits, and all 78 are already ancestors of `upstream/master`.** Checked individually with `git merge-base --is-ancestor <sha> upstream/master`, 78 of 78. So they are unmodified upstream history, already reviewed upstream, and nothing has been slipped in among them.
- **2 are yours**: `a34005435` (the sync) and `7a2aef033` (the conflict resolution).

The combined diff of the resolution commit, which is the part a human actually decided, is 22 files and +877/-9. Most of that is re-adding the upstream `muse-glimmer` arch and its mtmd pieces. It touches **no** fork-owned turbo or KV-cache code.

That makes this reviewable in a sitting, which the raw commit count does not suggest.

## The one fork-relevant change, and I think it is correct

`src/llama-kv-cache.{h,cpp}` loses a large block, net -283 lines in the cpp. That is the MSA indexer scaffolding: `k_idx`, `k_idx_stream`, `cpy_k_idx`, `msa_strict_slots`, `size_k_idx_bytes`, and the `has_k_idx` state serialization.

My first read was that this regressed MiniMax-M3, and I want to record that **I was wrong**, in case anyone else looks at the same diff and reaches for the same conclusion. Upstream restructured MSA so the indexer gets its own KV cache context, and `minimax-m3.cpp` on this branch uses that new design:

```cpp
const auto * mctx_idx = mctx_msa_l->get_idx();
ggml_build_forward_expand(gf, mctx_idx->cpy_k(ctx0, ik, inp_attn->get_k_idxs_idx(), il));
```

So the deletion is accepting an upstream improvement, not dropping a feature. Accepting it wholesale here looks right to me.

Worth being aware of one consequence: the `has_k_idx` fields disappear from the KV cache state serialization, so **session files written by the current fork will not be readable after this lands** for models that used the indexer cache. That is inherited from upstream rather than introduced here, but it is a user-visible break that should probably make the release notes.

The related point, that #288 partially re-adds this scaffolding as dead code, I have raised over there rather than here.

## Testing

Metal, this machine, M5 Max:

- base `d0e2a8b64`: builds clean, 537/537
- this stack through #289: builds clean, and `test-backend-ops` shows no regressions once compared case by case rather than by failure count

The `test-backend-ops` changes in here widen coverage and immediately surface pre-existing TQ3_1S and TQ4_1S bugs at large N, which I have folded into #285. Good outcome, and an argument for this landing.

CUDA is still unverified on my side. Our bench is busy, so that is queued rather than dropped, and I will report back on #288 when it runs.

**Comment by TheTom** [comment]
Following up on my earlier comment with a build result. **This PR does not compile on its own.** Since the point of the split is that each piece can land independently, and this one is first in the order, I wanted to flag it before you sequence the merges.

Checked out `7a2aef033` clean and built it, macOS, Metal, same cmake line as my earlier runs:

```
src/llama-kv-cache.cpp:421:38:  error: use of undeclared identifier 'k_idx'
src/llama-kv-cache.cpp:421:65:  error: use of undeclared identifier 'k_idx_stream'; did you mean 'k_stream'?
src/llama-kv-cache.cpp:2936:39: error: out-of-line definition of 'get_k_idx' does not match any declaration in 'llama_kv_cache_context'
src/llama-kv-cache.cpp:2937:16: error: no member named 'get_k_idx' in 'llama_kv_cache'
ninja: build stopped: subcommand failed.
```

Not Metal-specific. These are plain C++ errors in `src/`, so any backend and any platform will hit them.

## Cause

The MSA removal is 95 percent complete. Two references to the old design were left behind after the header declarations and the struct fields were dropped:

```cpp
// line 421, still passes two members the struct no longer has
layers.push_back({ il, k, v, k_idx, k_stream, v_stream, k_idx_stream });

// line 2936, definition whose declaration was removed from the header
ggml_tensor * llama_kv_cache_context::get_k_idx(ggml_context * ctx, int32_t il) const {
    return kv->get_k_idx(ctx, il, n_kv, sinfos[i_cur]);
}
```

## Fix, verified

Deleting both stragglers is sufficient. I applied exactly this locally and the build goes green, 444/444:

```diff
-        layers.push_back({ il, k, v, k_idx, k_stream, v_stream, k_idx_stream });
+        layers.push_back({ il, k, v, k_stream, v_stream });

-ggml_tensor * llama_kv_cache_context::get_k_idx(ggml_context * ctx, int32_t il) const {
-    return kv->get_k_idx(ctx, il, n_kv, sinfos[i_cur]);
-}
```

## Why I am suggesting deletion rather than your existing fix

You already fixed this, in `28896c45b` over on #288, which restores the fields and `get_k_idx` instead of removing the leftovers. That also compiles, so both directions work. I think **deletion is the right one**, for two reasons:

1. It keeps #287 self-contained. Right now the fix lives one PR downstream, so #287 cannot be merged first even though the split exists precisely so it can be.
2. Restoring re-adds dead code. As I noted on #288, after the restore `layers[].k_idx` is hardcoded `nullptr`, `get_k_idx` asserts it is non-null, and nothing anywhere calls `get_k_idx`. The MSA indexer now has its own cache and `minimax-m3.cpp` drives it via `mctx_msa_l->get_idx()`.

So the same two-line deletion fixes the build here and resolves the #288 comment at the same time.

## Otherwise the merge looks careful

Two things I checked that came out well, and which are worth stating since they are the ones that would have been expensive to discover late:

- **Turbo type enum values are untouched.** `TURBO2_0=43`, `TURBO3_0=44`, `TQ3_1S=45`, `TQ4_1S=46`, `TURBO4_0=47`, `GGML_TYPE_COUNT=48`, identical across this branch and the rest of the stack, and the whole `ggml_op` enum hashes byte-identical. No already-quantized GGUF is invalidated.
- **The new upstream MSA graph builder calls the fork's rotation inputs.** `build_attn_inp_kv_msa` invokes `build_input_k_rot` / `build_input_v_rot`, so TurboQuant rotation is correctly wired into the new path rather than bypassed. That was a deliberate act during the resolution, not luck.

I also ran a line-level sweep for fork code dropped by the roll-up: zero fork-added lines missing across all 246 fork-touched files. Validated the sweep against pristine upstream first, where it correctly reports the losses, so the zero is meaningful.

## One compatibility note for the release notes

For MSA-family models only, `minimax-m3` and friends, the KV cache state serialization layout changes, because the indexer moves from an interleaved block inside the main cache to its own cache instance. Saved sessions from before this lands will not load after it. Inherited from upstream rather than caused here, and it does not affect TurboQuant KV, DeepSeek-V4 or DFlash sessions, but users should be told.

**Comment by TheTom** [comment]
Confirmed fixed, thanks for the fast turnaround. Built `aab782c1b` clean on macOS/Metal:

```
PR287 @aab782c1b BUILD exit=0     errors: 0
```

Ran the gates on it as well:

| Gate | Result |
|---|---|
| `test-turbo-quant` | pass |
| `test-backend-ops` | 15 failing cases |

To be clear about that 15, since the number on its own looks bad and is not: it is **identical to the failing set on #289**, and I checked each one against the base branch. All are `MUL_MAT` sentinel mismatches on TQ3_1S and TQ4_1S at large N, none is a regression from this PR, and 9 of them are cases the base suite never generated at all, so your added test coverage is what surfaced them. That is tracked in #285 and is unrelated to this branch.

The one thing worth noting for anyone reading later: you fixed this by deleting the stragglers rather than restoring the fields, which means #288's `28896c45b` now restores scaffolding that no longer needs restoring. Once this lands, that hunk in #288 should probably come out so the dead `k_idx` field and the `get_k_idx` assert do not come back. That is the same thing I raised on #288, and it is now a one-line follow-up rather than a design question.

Nothing else blocking from me on this PR. Still queued on my side: the CUDA verification, which needs a bench that is currently busy.

**Comment by TheTom** [comment]
Pushed a fix to this branch, `60ee1d4b1`. Tom asked me to take this one over the line, so I went and root-caused the remaining CI failures rather than leaving them for you.

## The `test-chat` failure

The resolution took **upstream's `tests/test-chat.cpp`** but kept **the fork's older `common_chat_params_init_deepseek_v3_2`**. I checked this by hashing that function across four trees:

| Tree | `common_chat_params_init_deepseek_v3_2` |
|---|---|
| merge-base `89482bd66` | `fe00cff8...` |
| fork HEAD | `caf64496...` |
| **`aab782c1b` (this PR)** | **`caf64496...`** identical to the fork |
| `upstream/master` | `9255c464...` |

So the new upstream tests were asserting behaviour the older fork copy does not implement. Four things were missing:

1. `response_format` was not passed to the template as `additional_context`
2. `TC_SEPARATOR` (`"\n\n"`) was not accepted before a tool-call block
3. the `enable_thinking == false` continuation path emitted `<think></think>` where the template wants a bare `</think>`
4. `content_before_tools` did not tolerate the separator or trailing space

Item 3 is the one the assertion pointed at:

```
Expected: <｜Assistant｜></think>Hello,
Actual:   <｜Assistant｜><think></think>Hello,
```

The commit restores all four from upstream. **It deliberately keeps the fork's own change**, the tolerance for optional whitespace before `<think>` added in `1f7946026`, which upstream does not have. I checked that specifically rather than taking upstream's function wholesale, and re-ran a line-level sweep afterwards: 0 of the 200 fork-added lines in this file are missing.

## Local results on `60ee1d4b1`

```
build                : clean, 0 errors
test-chat            : [chat] All tests passed!
ctest                : 58/59
```

The single remaining failure is `test-backend-ops`, which is the pre-existing TQ3_1S/TQ4_1S large-N sentinel problem in #285. It fails identically on the base branch and is not caused by this PR.

## The other red jobs, triaged

I went through all of them so nobody has to guess:

| Bucket | Jobs | Verdict |
|---|---|---|
| Same `test-chat` bug | `ubuntu (arm64)`, `ubuntu-llvmpipe`, `windows (x64-cpu-static)`, both macOS jobs | fixed by this commit |
| Fail-fast cancellations of the above | `ubuntu (x64)`, `windows (x64-openblas)`, `windows (x64-vulkan)` | should clear too |
| Pre-existing, not this PR | `ubuntu-22-hip-quality-check`, the three SYCL jobs, Server `test_slot_save_restore` | see below |
| Self-hosted runner outage | all `gpu-*`, `cpu-*-high-perf`, `Lint`, `check-vendor`, `python type-check`, `update-ops-docs` | 0 steps ran, no runner ever picked them up, 24h queue timeout |

So one commit should take roughly 8 jobs green.

Two pre-existing bugs worth their own issues, both of which this PR does not touch and did not cause:

- **HIP**: `fattn-common.cuh:1409-1410`, ignoring a `nodiscard` `hipError_t` return, fatal under `-Werror`.
- **SYCL**: `ggml-sycl.cpp:5817`, a dead `return res;` after an unconditional return in the `GGML_OP_SET_ROWS` case of `supports_op`, referencing an undeclared identifier. One-line delete.

Both were verified to fail identically on an ancestor commit, so they predate this branch.

Thanks for splitting the stack, by the way. This was much easier to isolate as four PRs than it would have been as one.

**Comment by TheTom** [comment]
Merged as `cd84d3161`. @giveen you are unblocked, this is the one you were waiting on before starting the 287 -> 288 -> 289 -> 291 sequence.

Used a merge commit rather than a squash deliberately, so the 78 upstream commits keep their individual identity in the history. That lineage is what let me verify every one of them is an unmodified ancestor of `upstream/master`, and squashing would have thrown it away.

## Final CI

Every build and test job green, including all eight that the `test-chat` fix cleared:

```
macos-latest-arm64            macos-latest-x64        macos-latest-metal-offline-compile
ubuntu (arm64)                ubuntu (x64)            ubuntu-llvmpipe
windows (arm64)               windows (x64-cpu-static)
windows (x64-openblas)        windows (x64-vulkan)
cuda    musa    ubuntu-arm64  windows-2025-opencl-adreno
```

Six jobs remain red, all pre-existing and none caused by this PR:

| Job | Status |
|---|---|
| `ubuntu-24-sycl` fp16/fp32, `windows-latest-sycl` | fix in #293 |
| `ubuntu-22-hip-quality-check` | fix in #293 |
| `Server` ubuntu/windows | flaky `test_slot_save_restore`, seen identically on #288 and #289 |

The self-hosted GPU jobs never ran at all, zero steps, no runner picked them up. That fleet is down and is a separate operational problem.

## Post-merge verification on the merged commit itself

Not the PR head, the actual merge result:

```
build              : clean, 0 errors
test-turbo-quant   : pass
test-chat          : [chat] All tests passed!
```

## On fork work surviving the roll-up

Since this was the main risk, here is what was checked rather than assumed. Across the 21 files holding the TurboQuant kernels, quantization and compression work, **20 are untouched by the roll-up** and the one that is touched loses nothing:

| | |
|---|---|
| Fork-authored lines in those files | ~14,900 |
| Missing after the merge | **0** |
| `ggml-turbo-quant.c`, `turbo-quant.cuh`, `mmvq-tq.cu`, `set-rows.cu`, all four `fattn-*`, `ggml-metal.metal`, `turbo-matrices.h`, `copy_to_quant.comp`, the three SYCL turbo files, `turbo-rotation-data.h`, `llama-kv-cache-dsv4.cpp`, `deepseek4.cpp`, `dflash.cpp`, `test-turbo-quant.c` | untouched |
| `llama-kv-cache.cpp` | touched, 0 of 309 fork lines lost |

Type enum values are unchanged, `TURBO2_0=43` through `TURBO4_0=47` with `COUNT=48`, so no already-quantized GGUF is invalidated. The whole `ggml_op` enum hashes byte-identical. A per-commit pass over all 88 fork-unique commits came back INTACT for every one.

The only thing the roll-up removes is upstream's own older MSA indexer design, superseded by upstream's newer one, which `minimax-m3.cpp` now drives through `get_idx()`.

## Two things to carry forward

1. **MSA session files break.** For `minimax-m3` and family only, the indexer moves to its own cache instance and the on-disk KV layout changes. TurboQuant KV, DeepSeek-V4 and DFlash sessions are unaffected. Needs a release note.
2. **`--repeat-last-n -1` and `--dry-penalty-last-n -1` lose the "means ctx_size" sentinel.** Inherited from upstream, but it will silently change sampling for anyone whose launch scripts pass `-1`.

Thanks @giveen. Splitting the stack is what made this tractable, and holding off on the others while this landed was the right call.
