### ISSUE TITLE
SYCL reorder kernels undefined symbols

### ISSUE THREAD

**Issue by emcourtney1** [TheTom/llama-cpp-turboquant#314]
### Git commit

1c2034f4a2518ca89ba3f42eee7df6830f8b4bb2

### Operating systems

Linux

### GGML backends

SYCL

### Problem description & steps to reproduce

Just a regular build with SYCL enabled; cmake build --build. Compiler quit on llama-cpp-turboquant/ggml/src/ggml-sycl/mmvq.cpp complaining of undefined symbols. It's as simple problem really, I already fixed it locally and will file a pull request as soon as I figure out how. (wish me luck)

### First Bad Commit

c3a0487

### Compile command

```shell
cmake -B build -G Ninja   -DCMAKE_C_COMPILER=icx   -DCMAKE_CXX_COMPILER=icpx   -DGGML_SYCL=ON   -DGGML_SYCL_F16=ON   -DGGML_OPENMP=ON   -DCMAKE_BUILD_TYPE=Release
```

### Relevant log output

```shell
FAILED: ggml/src/ggml-sycl/CMakeFiles/ggml-sycl.dir/mmvq.cpp.o 
/opt/intel/oneapi/compiler/2026.1/bin/icpx -DGGML_BACKEND_BUILD -DGGML_BACKEND_SHARED -DGGML_SCHED_MAX_COPIES=4 -DGGML_SHARED -DGGML_SYCL_DNNL=1 -DGGML_SYCL_F16 -DGGML_SYCL_GRAPH -DGGML_SYCL_HOST_MEM_FALLBACK -DGGML_SYCL_SUPPORT_LEVEL_ZERO_API -DGGML_SYCL_TURBO_QUANT -DGGML_SYCL_WARP_SIZE=16 -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -Dggml_sycl_EXPORTS -I/home/evan/projects/temp/llama-cpp-turboquant/ggml/src/ggml-sycl/.. -I/home/evan/projects/temp/llama-cpp-turboquant/ggml/src/../include -isystem /opt/intel/oneapi/compiler/2026.1/include -isystem /opt/intel/oneapi/mkl/2026.1/include -O3 -DNDEBUG -std=gnu++17 -fPIC -Wmissing-declarations -Wmissing-noreturn -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-narrowing -fsycl -DMKL_ILP64 -MD -MT ggml/src/ggml-sycl/CMakeFiles/ggml-sycl.dir/mmvq.cpp.o -MF ggml/src/ggml-sycl/CMakeFiles/ggml-sycl.dir/mmvq.cpp.o.d -o ggml/src/ggml-sycl/CMakeFiles/ggml-sycl.dir/mmvq.cpp.o -c /home/evan/projects/temp/llama-cpp-turboquant/ggml/src/ggml-sycl/mmvq.cpp
/home/evan/projects/temp/llama-cpp-turboquant/ggml/src/ggml-sycl/mmvq.cpp:675:44: error: use of undeclared identifier 'block_nums'; did you mean 'block_num_y'?
  675 |         cgh.parallel_for(sycl::nd_range<3>(block_nums * block_dims, block_dims),
      |                                            ^~~~~~~~~~
      |                                            block_num_y
/home/evan/projects/temp/llama-cpp-turboquant/ggml/src/ggml-sycl/mmvq.cpp:669:22: note: 'block_num_y' declared here
  669 |     const int        block_num_y   = ceil_div(nrows, GGML_SYCL_MMV_Y * (int) num_subgroups) * (int) num_subgroups;
      |                      ^
/home/evan/projects/temp/llama-cpp-turboquant/ggml/src/ggml-sycl/mmvq.cpp:675:57: error: use of undeclared identifier 'block_dims'
  675 |         cgh.parallel_for(sycl::nd_range<3>(block_nums * block_dims, block_dims),
      |                                                         ^~~~~~~~~~
```

**Comment by giveen** [comment]
@emcourtney1 , create a fork of the project onto your github, then create a branch, place your patches on that branch, then open a PR

**Comment by TheTom** [comment]
Fixed on current head. The reorder launch now defines global_size and workgroup_size directly from block_num_y instead of referring to the undefined block_nums/block_dims names. Thanks for reporting the exact compiler failure.
