### ISSUE TITLE
Compile bug: windows + vulkan

### ISSUE THREAD

**Issue by Ezzz-dev** [TheTom/llama-cpp-turboquant#89]
### Git commit

latest

### Operating systems

Windows

### GGML backends

Vulkan

### Problem description & steps to reproduce

Just trying to compile with Vulkan in Windows

### Compile command

```shell
cmake -B build -DGGML_VULKAN=ON
cmake --build build --config Release
```

### Relevant log output

```shell
C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\ggml\src\ggml-vulkan\ggml-vulkan.cpp(4452,105): error C2065: '
cpy_f32_q4_0_rte_len': undeclared identifier [C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\build\ggml\src\g
gml-vulkan\ggml-vulkan.vcxproj]
C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\ggml\src\ggml-vulkan\ggml-vulkan.cpp(4452,127): error C2065: '
cpy_f32_q4_0_rte_data': undeclared identifier [C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\build\ggml\src\
ggml-vulkan\ggml-vulkan.vcxproj]
C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\ggml\src\ggml-vulkan\ggml-vulkan.cpp(4453,105): error C2065: '
cpy_f32_q4_1_rte_len': undeclared identifier [C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\build\ggml\src\g
gml-vulkan\ggml-vulkan.vcxproj]
C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\ggml\src\ggml-vulkan\ggml-vulkan.cpp(4453,127): error C2065: '
cpy_f32_q4_1_rte_data': undeclared identifier [C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\build\ggml\src\
ggml-vulkan\ggml-vulkan.vcxproj]
C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\ggml\src\ggml-vulkan\ggml-vulkan.cpp(4454,105): error C2065: '
cpy_f32_q5_0_rte_len': undeclared identifier [C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\build\ggml\src\g
gml-vulkan\ggml-vulkan.vcxproj]
C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\ggml\src\ggml-vulkan\ggml-vulkan.cpp(4454,127): error C2065: '
cpy_f32_q5_0_rte_data': undeclared identifier [C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\build\ggml\src\
ggml-vulkan\ggml-vulkan.vcxproj]
C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\ggml\src\ggml-vulkan\ggml-vulkan.cpp(4455,105): error C2065: '
cpy_f32_q5_1_rte_len': undeclared identifier [C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\build\ggml\src\g
gml-vulkan\ggml-vulkan.vcxproj]
C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\ggml\src\ggml-vulkan\ggml-vulkan.cpp(4455,127): error C2065: '
cpy_f32_q5_1_rte_data': undeclared identifier [C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\build\ggml\src\
ggml-vulkan\ggml-vulkan.vcxproj]
C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\ggml\src\ggml-vulkan\ggml-vulkan.cpp(4456,105): error C2065: '
cpy_f32_q8_0_rte_len': undeclared identifier [C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\build\ggml\src\g
gml-vulkan\ggml-vulkan.vcxproj]
C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\ggml\src\ggml-vulkan\ggml-vulkan.cpp(4456,127): error C2065: '
cpy_f32_q8_0_rte_data': undeclared identifier [C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\build\ggml\src\
ggml-vulkan\ggml-vulkan.vcxproj]
C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\ggml\src\ggml-vulkan\ggml-vulkan.cpp(4457,109): error C2065: '
cpy_f32_iq4_nl_rte_len': undeclared identifier [C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\build\ggml\src
\ggml-vulkan\ggml-vulkan.vcxproj]
C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\ggml\src\ggml-vulkan\ggml-vulkan.cpp(4457,133): error C2065: '
cpy_f32_iq4_nl_rte_data': undeclared identifier [C:\Users\soyal\OneDrive\Desktop\git\llama-cpp-turboquant\build\ggml\sr
c\ggml-vulkan\ggml-vulkan.vcxproj]
  C:/VulkanSDK/1.4.341.1/Bin/glslc.exe -fshader-stage=compute --target-env=vulkan1.2 "C:/Users/soyal/OneDrive/Desktop/g
  it/llama-cpp-turboquant/ggml/src/ggml-vulkan/vulkan-shaders/flash_attn.comp" -o "C:/Users/soyal/OneDrive/Desktop/git/
  llama-cpp-turboquant/build/ggml/src/ggml-vulkan/vulkan-shaders.spv/flash_attn_f32_f16_turbo3_0_fp32_int8.spv" -O -DAC
  C_TYPE=float -DACC_TYPEV2=vec2 -DACC_TYPEV4=vec4 -DBLOCK_SIZE=QUANT_K_TURBO3_0 -DDATA_A_TURBO3_0=1 -DD_TYPE=float -DD
  _TYPEV4=vec4 -DFLOAT_TYPE=float -DFLOAT_TYPEV2=vec2 -DFLOAT_TYPEV4=vec4 -DMMQ=1 -DQ_TYPE=float

  C:/Users/soyal/OneDrive/Desktop/git/llama-cpp-turboquant/ggml/src/ggml-vulkan/vulkan-shaders/flash_attn.comp:72: erro
  r: '' :  syntax error, unexpected IDENTIFIER, expecting COMMA or SEMICOLON
```

**Comment by diamondT** [comment]
getting the same error also on linux so maybe not windows specific? plus another error for `"SET_ROWS"`

the first bad commit appears to be `a494833d0dbf46f01fe98653b6c45e403886ae88`


```
cmake -B build-vulkan -DCMAKE_BUILD_TYPE=Release -DGGML_VULKAN=ON -DGGML_SCHED_MAX_COPIES=1
cmake --build build-vulkan --config Release -j8
```

```
[  7%] Building CXX object ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/ggml-vulkan.cpp.o
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4481:18: error: macro ‘SET_ROWS’ requires 2 arguments, but only 1 given
 4481 |     SET_ROWS(_i32)
      |                  ^
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4468:9: note: macro ‘SET_ROWS’ defined here
 4468 | #define SET_ROWS(itype, rte) \
      |         ^~~~~~~~
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4482:18: error: macro ‘SET_ROWS’ requires 2 arguments, but only 1 given
 4482 |     SET_ROWS(_i64)
      |                  ^
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4468:9: note: macro ‘SET_ROWS’ defined here
 4468 | #define SET_ROWS(itype, rte) \
      |         ^~~~~~~~
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp: In function ‘void ggml_vk_load_shaders(vk_device&)’:
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4452:105: error: ‘cpy_f32_q4_0_rte_len’ was not declared in this scope; did you mean ‘cpy_f32_q4_0_len’?
 4452 |         ggml_vk_create_pipeline(device, device->pipeline_cpy_f32_quant[GGML_TYPE_Q4_0], "cpy_f32_q4_0", cpy_f32_q4_0_rte_len, cpy_f32_q4_0_rte_data, "main", 2, sizeof(vk_op_unary_push_constants), {32, 1, 1}, {}, 1);
      |                                                                                                         ^~~~~~~~~~~~~~~~~~~~
      |                                                                                                         cpy_f32_q4_0_len
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4452:127: error: ‘cpy_f32_q4_0_rte_data’ was not declared in this scope; did you mean ‘cpy_f32_q4_0_data’?
 4452 |         ggml_vk_create_pipeline(device, device->pipeline_cpy_f32_quant[GGML_TYPE_Q4_0], "cpy_f32_q4_0", cpy_f32_q4_0_rte_len, cpy_f32_q4_0_rte_data, "main", 2, sizeof(vk_op_unary_push_constants), {32, 1, 1}, {}, 1);
      |                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                               cpy_f32_q4_0_data
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4453:105: error: ‘cpy_f32_q4_1_rte_len’ was not declared in this scope; did you mean ‘cpy_f32_q4_1_len’?
 4453 |         ggml_vk_create_pipeline(device, device->pipeline_cpy_f32_quant[GGML_TYPE_Q4_1], "cpy_f32_q4_1", cpy_f32_q4_1_rte_len, cpy_f32_q4_1_rte_data, "main", 2, sizeof(vk_op_unary_push_constants), {32, 1, 1}, {}, 1);
      |                                                                                                         ^~~~~~~~~~~~~~~~~~~~
      |                                                                                                         cpy_f32_q4_1_len
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4453:127: error: ‘cpy_f32_q4_1_rte_data’ was not declared in this scope; did you mean ‘cpy_f32_q4_1_data’?
 4453 |         ggml_vk_create_pipeline(device, device->pipeline_cpy_f32_quant[GGML_TYPE_Q4_1], "cpy_f32_q4_1", cpy_f32_q4_1_rte_len, cpy_f32_q4_1_rte_data, "main", 2, sizeof(vk_op_unary_push_constants), {32, 1, 1}, {}, 1);
      |                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                               cpy_f32_q4_1_data
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4454:105: error: ‘cpy_f32_q5_0_rte_len’ was not declared in this scope; did you mean ‘cpy_f32_q5_0_len’?
 4454 |         ggml_vk_create_pipeline(device, device->pipeline_cpy_f32_quant[GGML_TYPE_Q5_0], "cpy_f32_q5_0", cpy_f32_q5_0_rte_len, cpy_f32_q5_0_rte_data, "main", 2, sizeof(vk_op_unary_push_constants), {32, 1, 1}, {}, 1);
      |                                                                                                         ^~~~~~~~~~~~~~~~~~~~
      |                                                                                                         cpy_f32_q5_0_len
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4454:127: error: ‘cpy_f32_q5_0_rte_data’ was not declared in this scope; did you mean ‘cpy_f32_q5_0_data’?
 4454 |         ggml_vk_create_pipeline(device, device->pipeline_cpy_f32_quant[GGML_TYPE_Q5_0], "cpy_f32_q5_0", cpy_f32_q5_0_rte_len, cpy_f32_q5_0_rte_data, "main", 2, sizeof(vk_op_unary_push_constants), {32, 1, 1}, {}, 1);
      |                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                               cpy_f32_q5_0_data
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4455:105: error: ‘cpy_f32_q5_1_rte_len’ was not declared in this scope; did you mean ‘cpy_f32_q5_1_len’?
 4455 |         ggml_vk_create_pipeline(device, device->pipeline_cpy_f32_quant[GGML_TYPE_Q5_1], "cpy_f32_q5_1", cpy_f32_q5_1_rte_len, cpy_f32_q5_1_rte_data, "main", 2, sizeof(vk_op_unary_push_constants), {32, 1, 1}, {}, 1);
      |                                                                                                         ^~~~~~~~~~~~~~~~~~~~
      |                                                                                                         cpy_f32_q5_1_len
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4455:127: error: ‘cpy_f32_q5_1_rte_data’ was not declared in this scope; did you mean ‘cpy_f32_q5_1_data’?
 4455 |         ggml_vk_create_pipeline(device, device->pipeline_cpy_f32_quant[GGML_TYPE_Q5_1], "cpy_f32_q5_1", cpy_f32_q5_1_rte_len, cpy_f32_q5_1_rte_data, "main", 2, sizeof(vk_op_unary_push_constants), {32, 1, 1}, {}, 1);
      |                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                               cpy_f32_q5_1_data
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4456:105: error: ‘cpy_f32_q8_0_rte_len’ was not declared in this scope; did you mean ‘cpy_f32_q8_0_len’?
 4456 |         ggml_vk_create_pipeline(device, device->pipeline_cpy_f32_quant[GGML_TYPE_Q8_0], "cpy_f32_q8_0", cpy_f32_q8_0_rte_len, cpy_f32_q8_0_rte_data, "main", 2, sizeof(vk_op_unary_push_constants), {32, 1, 1}, {}, 1);
      |                                                                                                         ^~~~~~~~~~~~~~~~~~~~
      |                                                                                                         cpy_f32_q8_0_len
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4456:127: error: ‘cpy_f32_q8_0_rte_data’ was not declared in this scope; did you mean ‘cpy_f32_q8_0_data’?
 4456 |         ggml_vk_create_pipeline(device, device->pipeline_cpy_f32_quant[GGML_TYPE_Q8_0], "cpy_f32_q8_0", cpy_f32_q8_0_rte_len, cpy_f32_q8_0_rte_data, "main", 2, sizeof(vk_op_unary_push_constants), {32, 1, 1}, {}, 1);
      |                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                               cpy_f32_q8_0_data
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4457:109: error: ‘cpy_f32_iq4_nl_rte_len’ was not declared in this scope; did you mean ‘cpy_f32_iq4_nl_len’?
 4457 |         ggml_vk_create_pipeline(device, device->pipeline_cpy_f32_quant[GGML_TYPE_IQ4_NL], "cpy_f32_iq4_nl", cpy_f32_iq4_nl_rte_len, cpy_f32_iq4_nl_rte_data, "main", 2, sizeof(vk_op_unary_push_constants), {32, 1, 1}, {}, 1);
      |                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                             cpy_f32_iq4_nl_len
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4457:133: error: ‘cpy_f32_iq4_nl_rte_data’ was not declared in this scope; did you mean ‘cpy_f32_iq4_nl_data’?
 4457 |         ggml_vk_create_pipeline(device, device->pipeline_cpy_f32_quant[GGML_TYPE_IQ4_NL], "cpy_f32_iq4_nl", cpy_f32_iq4_nl_rte_len, cpy_f32_iq4_nl_rte_data, "main", 2, sizeof(vk_op_unary_push_constants), {32, 1, 1}, {}, 1);
      |                                                                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                     cpy_f32_iq4_nl_data
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4481:5: error: ‘SET_ROWS’ was not declared in this scope
 4481 |     SET_ROWS(_i32)
      |     ^~~~~~~~
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4486:233: error: expected primary-expression before ‘,’ token
 4486 | evice->pipeline_cpy_quant_f32[GGML_TYPE_Q1_0], "cpy_q1_0_f32", cpy_q1_0_f32_len, cpy_q1_0_f32_data, "main", 2, sizeof(vk_op_unary_push_constants), {(uint32_t)ggml_blck_size(GGML_TYPE_Q1_0), 1, 1}, {}, 1);
      |                                                                                                                                                                                                    ^
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4486:235: error: expected primary-expression before ‘{’ token
 4486 | evice->pipeline_cpy_quant_f32[GGML_TYPE_Q1_0], "cpy_q1_0_f32", cpy_q1_0_f32_len, cpy_q1_0_f32_data, "main", 2, sizeof(vk_op_unary_push_constants), {(uint32_t)ggml_blck_size(GGML_TYPE_Q1_0), 1, 1}, {}, 1);
      |                                                                                                                                                                                                      ^
~/playground/llama-cpp-turboquant/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4486:237: error: expected primary-expression before ‘,’ token
 4486 | evice->pipeline_cpy_quant_f32[GGML_TYPE_Q1_0], "cpy_q1_0_f32", cpy_q1_0_f32_len, cpy_q1_0_f32_data, "main", 2, sizeof(vk_op_unary_push_constants), {(uint32_t)ggml_blck_size(GGML_TYPE_Q1_0), 1, 1}, {}, 1);
      |                                                                                                                                                                                                        ^
gmake[2]: *** [ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/build.make:1013: ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/ggml-vulkan.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2416: ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```

**Comment by diamondT** [comment]
update: looks fine now with `4d24ad87b`
